# Configuration of workflows

log_level: debug
#log_level: info

# Remote buckets to sync to/from
remotes:
  - name: minio1
    endpoint: minio.golder.lan
    accessKey: youraccesskey
    secretKey: yoursecretkey

# Outbound means files that arrive locally that are to be sent to S3, with or without
# pre-processing being applied.
outbound:
  - name: KSK1
    description: Kasikorn Main Company Account
    sensitive: false
    source: "/home/rossg/Downloads/bank-statements-company/kasikorn-rossgolderltd/*"
    destination: "s3://minio.golder.lan/bank-statements-company/kasikorn-rossgolderltd"
    process_with: "/home/rossg/obfuscate"

  - name: KSK2
    description: Kasikorn Credit Card Account
    source: "/home/rossg/Downloads/bank-statements-company/kasikorn-rasamee/*"
    destination: "s3://minio.golder.lan/bank-statements-company/kasikorn-rasamee"
    sensitive: false

  - name: KSK3
    description: Kasikorn Main Family Account
    source: "/home/rossg/Downloads/bank-statements-family/kasikorn-rossigee/*"
    destination: "s3://minio.golder.lan/bank-statements-family/kasikorn-rossigee"
    sensitive: false

# Inbound means files that should be retrieved from S3 to the local machine when we
# receive an SQS notification that a new file has been deposited.
inbound:
  - name: FAMILY
    description: Family Document Scans
    source: "amqp://bucketsyncd:somepassword@amqp.golder.lan/document-scans"
    exchange: "family-scans"
    queue: "scans-to-desktop"
    remote: minio1
    destination: "/home/rossg/Downloads"

  - name: COMPANY
    description: Company Document Scans
    source: "amqp://bucketsyncd:somepassword@amqp.golder.lan/document-scans"
    exchange: "company-scans"
    queue: "scans-to-desktop"
    remote: minio1
    destination: "/home/rossg/Downloads"
